-- Table: public.Persons

-- DROP TABLE IF EXISTS public."Persons";

CREATE TABLE IF NOT EXISTS public."Persons"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "FirstName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "LastName" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "DoB" date NOT NULL,
    CONSTRAINT "Persons_pkey" PRIMARY KEY ("Id")
)